### ISSUE TITLE
Unresponsive browser after permissions request

### ISSUE THREAD

**Issue by diegomazala** [zappar-xr/universal-ar-unity#1]
**Describe the bug**
The application become unresponsive after user grant the camera/sensor permissions. It does not update the browser after finishing the call. 
The camera permission is an example. Once the permission is granted, the permission ui is hidden and the unity render screen is revealed. However, it is unresponsive. 
The user has to refresh the browser to have the behavior normalized.
Notice: if you have the permissions given, the error does not manifest. So, clear the browser history to see the issue.

**To Reproduce**
1. Used UAR version 1.1.1-preview_1
2. With Unity version 2020.3.12f1 using SRP (No) and build platform as WebGL 
3. Describe the unity scene setup - You can have the minimum setup to ask for permissions.  
> Canvas with a text showing Time.time
> Script with two calls: Z.Initialize() and Z.PermissionRequestUi()

**Expected behavior**
I expected to have the game/app playing normally after requesting permissions without having to refresh the browser

**Screenshots**
![image](https://user-images.githubusercontent.com/5922694/126974579-36d0dd8b-c637-4206-8622-e678bc0f4b78.png)

**Desktop **
 - Issue does not manifest

**Smartphone (please complete the following information):**
 - Device: Samsung S10
 - OS: Android 11
 - Browser Google Chrome
 - Version 92.0.4515.115

[ZapparTest.txt](https://github.com/zappar-xr/universal-ar-unity/files/6877473/ZapparTest.txt)

**Comment by diegomazala** [comment]
Adding more information.
The result of calling Z.PermissionRequestUi() or Z.PermissionRequestCamera() is the same.
Of course, they are called after Z.HasInitialized()==true

The browser doesn't respond unless I refresh or change tabs

**Comment by nfynt-zap** [comment]
Thanks for trying our package @diegomazala 

With a quick reproduce step, we didn't encounter any freezing on android/iOS browser. Are you still encountering this issue? If so can you share any console log (if relevant) or stripped minimum project which we can test. 

Further note that you'll need to test the webgl build from a HTTPS server (either publicly hosted or self signed locally i.e. [Zapworks CLI](https://docs.zap.works/universal-ar/zapworks-cli/)). General HTTP server doesn't allow camera access which may be the reason in your case.

Cheers
