### ISSUE TITLE
Dark Camera on iOS

### ISSUE THREAD

**Issue by Archi97** [zappar-xr/universal-ar-unity#11]
**Describe the bug**
Zappar camera is Darker compared with default camera.  Why and how to fix?
![image](https://user-images.githubusercontent.com/36793459/175893370-4ac96600-ec46-48d7-a601-7f220239f6b1.png)

**Smartphone (please complete the following information):**
 - Device: Iphone all versions
 - OS: 13+,14+,15+
 - Version Zappar version 3.0.1

**Comment by nfynt-zap** [comment]
Thanks @Archi97 
It seems this one's a bug on our side and limited to metal graphics API. I'll have it fixed in the next release, and in the mean time you can try the following patch:

In Z.cs line:580 replace this:
```
texture = Texture2D.CreateExternalTexture(4, 4, TextureFormat.ARGB32, false, false, ptr);
```
with this:
```
if (SystemInfo.graphicsDeviceType == GraphicsDeviceType.Metal)
    texture = Texture2D.CreateExternalTexture(4, 4, TextureFormat.ARGB32, false, true, ptr);
else
    texture = Texture2D.CreateExternalTexture(4, 4, TextureFormat.ARGB32, false, false, ptr);
```

**Comment by Archi97** [comment]
@nfynt-zap  tried what you said. but didn't work. same result(maybe a bit different)

**Comment by nfynt-zap** [comment]
Thanks for reporting this @Archi97

While we fix this at the root level, you can try either of the following two approaches to work around this for now:
1. Switch to `Linear` Color space mode from `Project Settings/Player/Other Settings`.

2. Download the new [ZapparCameraBackground.cs](https://drive.google.com/file/d/1Fp709bFq7Av_iuX1CJeGHi6IqV8rGo_8/view?usp=sharing) and [CameraBackgroundShader.shader](https://drive.google.com/file/d/1tkb6C_msBGk6tMOgr6cN7ec__XmeOLbm/view?usp=sharing) and replace them in respective directories of `@uar/Runtime/` and `@uar/Resources/Shader/`, which will take care of gamma correction. Next, in `ZapparCameraBackground` script in your scene, you would want to set the `Gamma Correction` value as 2.2, though feel free to set it as per your requirement.
![image](https://user-images.githubusercontent.com/84909983/176151070-15c49a17-861f-40a0-8e66-8082a0626710.png)

Note that this is meant as temporary fix only and I'll update this thread when we have an official fix released for this.

Best,

**Comment by Archi97** [comment]
@nfynt-zap thank you. i have tried 2-n version. Works great.
