### ISSUE TITLE
Camera Freeze on long use

### ISSUE THREAD

**Issue by Archi97** [zappar-xr/universal-ar-unity#13]
Maybe the last bug from my side. 
On Android on long use(tested like this, opened camera, set  screen not to sleep), Zappar Camera freezes. Only restart make it work again. 

Android 9,10,11,12
Unity 2020.3.15f2
Zappar 3.0.1

**Comment by nfynt-zap** [comment]
Did you register your android package id on the Zapworks distribution hub?

Also, please take time to provide as many details as possible about the issue... esp. steps to reproduce, logs, screenshots, etc, which would aid us in better understanding the issue and providing a more accurate response, for a quick resolution.
