### ISSUE TITLE
Unity on MacOS Silicon

### ISSUE THREAD

**Issue by eduhalfen** [zappar-xr/universal-ar-unity#14]
Is there any problem in running on Mac OS with Silicon? I can't run properly in this machine.

**Comment by nfynt-zap** [comment]
Support for Unity silicon editor is currently in development and not out yet. 
Though not ideal, the intel version of Unity should work in the meantime.

**Comment by eduhalfen** [comment]
Thank you

**Comment by gushenjie** [comment]
Is it supported now?

**Comment by nfynt-zap** [comment]
The newest release of version `https://github.com/zappar-xr/universal-ar-unity.git#3.2.0`  should fix this. 

Can you give it a try?
