### ISSUE TITLE
Error compiling Zappar on linux

### ISSUE THREAD

**Issue by SalamanderXing** [zappar-xr/universal-ar-unity#17]
**Describe the bug**
Following the documentation on https://docs.zap.works/universal-ar/unity/getting-started/importing/
I installed zappar in the package manager. But during compilation I get the following error:

Library/PackageCache/com.zappar.uar@6025ba0657/Editor/ImageTrain/ZImageTrainer.cs(284,15): error CS0426: The type name 'FileData' does not exist in the type 'Z'

**To Reproduce**
1. With Unity version '2021.3.18f1' using WebGL
2. From UnityHub I created a 3D project. No other changes were made
3. See error

**Expected behavior**
I expected no errors during compilation

**Screenshots**
![2023-02-11_11-40](https://user-images.githubusercontent.com/6129632/218258479-2afe8aa3-0578-4c9d-889b-58206580f21b.png)

**Desktop (please complete the following information):**
 - OS:  On Linux 6.1.9-arch1-1

**Comment by nfynt-zap** [comment]
Thanks for trying our SDK, but we don't support the Linux platform yet. You can read more about In-editor (Mac and Win only) and Build (WebGL, iOS, and Android only) platform support here: 
https://github.com/zappar-xr/universal-ar-unity#platform-support.
