### ISSUE TITLE
Package Cannot Install

### ISSUE THREAD

**Issue by lijualivenow** [zappar-xr/universal-ar-unity#2]
Package cannot install from https://github.com/zappar-xr/universal-ar-unity.git

Unity Version :2019.4.20f1

Following error is showing

Cannot perform upm operation: Unable to add package [https://github.com/zappar-xr/universal-ar-unity.git]:
  No 'git' executable was found. Please install Git on your system then restart Unity and Unity Hub [NotFound]
UnityEditor.EditorApplication:Internal_CallUpdateFunctions()

**Comment by nyan-left** [comment]
Hi @lijualivenow ,

You need to install git. Download it here:
https://git-scm.com/downloads
