### ISSUE TITLE
The type name 'FileData' does not exist in the type 'Z' on initial project start

### ISSUE THREAD

**Issue by nevyn** [zappar-xr/universal-ar-unity#20]
**Describe the bug**

Launching a plain 3D core project with the zappar plugin added to manifest.json like so:

```
    "com.zappar.uar": "https://github.com/zappar-xr/universal-ar-unity.git"
```

yields the following error on start:

![image](https://user-images.githubusercontent.com/34791/232330260-03f30f18-90e9-4e60-a65e-5703a9f96c70.png)

**To Reproduce**

1. Used UAR version 3.2.0
2. With Unity version 2021.3.23f1
3. with a plain new project from 3d template with no changes

**Expected behavior**
project to not crash on first launch

**Screenshots**
![image](https://user-images.githubusercontent.com/34791/232330260-03f30f18-90e9-4e60-a65e-5703a9f96c70.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: Firefox

**Comment by nfynt-zap** [comment]
As mentioned on a similar issue here #17, we do not support any linux based OS yet. It's something on our board but no plans for adding this support in near future. So I would encourage you to try either Windows and Mac OS for development.

Best
