### ISSUE TITLE
Package install doesn't work for Unity version 2020.3

### ISSUE THREAD

**Issue by charan-vendra** [zappar-xr/universal-ar-unity#21]
## **Description:**

Recieving two errors:

> Library\PackageCache\com.zappar.uar@30ba9c2d01\Editor\ZAssistant.cs(94,68): error CS0103: The name 'WebGLTextureSubtarget' does not exist in the current context

> Library\PackageCache\com.zappar.uar@30ba9c2d01\Editor\ZAssistant.cs(94,45): error CS0117: 'EditorUserBuildSettings' does not contain a definition for 'webGLBuildSubtarget'

This is due to the fact that Unity 2020.3 doesn't have these two properties.

## **To Reproduce**
1. With Unity version '2020.3.25' and build platform as 'webGL'.
2. Install the package using package manager.
3. See error.

## **Expected behavior**
Install in editor without problems.

## **Additional context**
My particular Unity version is `2020.3.25f1`

**Comment by nfynt-zap** [comment]
Thanks for reporting this @charan-vendra 

Indeed the `webGLBuildSubtarget` API under `EditorUserBuildSettings` is only available from 2021.2.x. 

Few ways to resolve this would be:
i) Switch to either 2021 LTS or fallback to 2019 LTS
ii) Download this repo locally and reference in editor as local UPM. Then change the line [here ](https://github.com/zappar-xr/universal-ar-unity/blob/main/Editor/ZAssistant.cs#L93) with `UNITY_2021_2_OR_NEWER`

Personally I would recommed updating to more recent Unity 2021 LTS to get the best performance and LTS support. Till we fix this on the main branch.

Best,

**Comment by nfynt-zap** [comment]
Fixed in UAR version 3.2.2
