### ISSUE TITLE
Can't run my unity webGL project on zappar, also no imports work in Unity

### ISSUE THREAD

**Issue by jv1000** [zappar-xr/universal-ar-unity#24]
Wrote a super simple Unity AR project. When I zipped it and tried to display on zappar, I get this message:
<img width="134" alt="image" src="https://github.com/zappar-xr/universal-ar-unity/assets/51660708/cf1ac188-e720-448f-9011-66ef9927e213">

please help

**Comment by nfynt-zap** [comment]
Pretty sure you forgot to select the appropriate Zappar WebGL Template before building your project. Please follow the instructions as mentioned [here](https://github.com/zappar-xr/universal-ar-unity#webgl).

Feel free to reopen this issue if that's not the case.
