### ISSUE TITLE
I want a plane detection display lattice function

### ISSUE THREAD

**Issue by woaizhouying** [zappar-xr/universal-ar-unity#25]
Like the official unity effect, it can detect vertical or parallel planes. Hopefully, it will be updated in the unity SDK next time

**Comment by woaizhouying** [comment]
Anyone here？

**Comment by nfynt-zap** [comment]
Hi @woaizhouying ,
there's no support for surface tracking (horizontal or vertical plane) or meshing in our SDK. 

Our instant and world tracking uses sparse set of minimum feature points that are performant and light enough to be supported on web, and thus it's not really feature-comparable to native arcore/arkit.  Hope this helps to clarify.
