### ISSUE TITLE
Blendshapes

### ISSUE THREAD

**Issue by Dalla-Inceptive** [zappar-xr/universal-ar-unity#26]
Greetings 
I'm developing a face filter using Zappar SDK in order to develop it I need to get the values of the expressions (they have to be 52 blend shapes)  
So when I get them I apply them to my Avatar
How to do that since you only provide 29 expression value ?
Thanks

**Comment by nfynt-zap** [comment]
Greeting @Dalla-Inceptive 
I am afraid there's no support for Blendshapes on the SDK side. Even the 29 expression coefficients are updated w.r.t. default face mesh model, so I doubt that it can be used with any random mesh reliably. However feel free to experiment on your end.
Further regarding face filter, I reckon you should be able to swap the material of default face mesh, and for any other embellishment make use of the [Face Landmark](https://github.com/zappar-xr/universal-ar-unity?tab=readme-ov-file#face-landmark) for placement.
Hope that helps.
