### ISSUE TITLE
srihari.mekala111@gmail.com

### ISSUE THREAD

**Issue by Sriharry** [zappar-xr/universal-ar-unity#28]
EntryPointNotFoundException: zappar_free assembly:<unknown assembly> type:<unknown type> member:(null)
Zappar.Z.PipelineProjectionMatrix (System.IntPtr o, System.Int32 renderWidth, System.Int32 renderHeight, System.Single zNear, System.Single zFar, System.Single[]& cameraModel) (at ./Library/PackageCache/com.zappar.uar@70ccba4de0/Runtime/Z.cs:611)
Zappar.ZapparBaseCameraBackground.Update () (at ./Library/PackageCache/com.zappar.uar@70ccba4de0/Runtime/ZapparBaseCameraBackground.cs:108)

**Comment by giganticlab** [comment]
same problem

**Comment by desarrolloserotav** [comment]
I've the same error

**Comment by cgauld** [comment]
Hi @Sriharry @giganticlab @desarrolloserotav thanks for you patience, this is now fixed :-) You should be able to pull the latest version from the Github URL. Let us know if you encounter any further issues.
