### ISSUE TITLE
App Crashing on long use.

### ISSUE THREAD

**Issue by Archi97** [zappar-xr/universal-ar-unity#9]
**Describe the bug**
Hello. I have a game, Start scene is not with camera.  After selecting some options the scene with Zap camera is loading. 
Without doing nothing(just keeping camera on), it is getting crushed after 5-10 minute. 
Nothing special in the Profiler, Expect this error message. 

Autoconnected Player OPENGL NATIVE PLUG-IN ERROR: GL_INVALID_VALUE: Numeric argument out of range
Zappar.ZapparCamera:Update()

[./Runtime/GfxDevice/opengles/GfxDeviceGLES.cpp line 1322570616]

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy Note 10+
 - OS: Android 12
 - Browser Chrome
 - Version ??

**Comment by nfynt-zap** [comment]
Can you provide any public test URL for your project? And it would also help if you can try following steps:
- Take a debug webgl build with full exception support.
- Using WebGL 1.0 (ES2) graphics API instead of WebGL 2.0 (ES3).

You can find the package version under the UAR settings in the editor or `package.json` file.

**Comment by Archi97** [comment]
> Can you provide any public test URL for your project? And it would also help if you can try following steps:
> 
> * Take a debug webgl build with full exception support.
> * Using WebGL 1.0 (ES2) graphics API instead of WebGL 2.0 (ES3).
> 
> You can find the package version under the UAR settings in the editor or `package.json` file.

I did some tests. Before opening the scene with Zap camera, im using scene with Vuforia camera. 
In that case Zap camera crashes after some time. But without initing Vuforia, game works great.

**Comment by nfynt-zap** [comment]
I see... Not sure we can do anything in this regard. You may wanna inspect Vuforia's pipeline closely to see what's happening.
Feel free to reopen this if you find any new information.

**Comment by Archi97** [comment]
Hello There. I'm back with another question. 
I have changed Vuforia Scanner to Zappar scanner(as I just realized that it is possible).
Now when I'm scanning image then switching scene, some times 2nd scene is full black(where I'm trying to track face), like camera is not working. 
I tested in that case Zapper initialized.
What can be wrong?

**Comment by Archi97** [comment]
Mostly on Xiamies

**Comment by nfynt-zap** [comment]
I haven't come across such behaviour on android... so it's likely specific to your project or scene setup. Can you share some test URL or reproducible setup for this?

**Comment by Archi97** [comment]
Please close this
